---
name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    env:
      lazarus_windows_cache: ${{ runner.temp }}\lazarus-installer

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # ---------- LINUX ----------
      - name: Build on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -xeuo pipefail
          sudo bash -c 'apt-get update; apt-get install -y lazarus libxtst-dev' >/dev/null
          instantfpc -Fu/usr/lib/lazarus/*/components/lazutils .github/workflows/make.pas
          delp -r "${PWD}"

      # ---------- WINDOWS ----------
      - name: Cache Lazarus installer on Windows
        if: runner.os == 'Windows'
        id: cache-lazarus
        uses: actions/cache@v4
        with:
          path: ${{ env.lazarus_windows_cache}}
          key: ${{ runner.os }}-lazarus-installer-4.0

      - name: Download Lazarus installer if not cached on Windows
        if: runner.os == 'Windows' && steps.cache-lazarus.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "$Env:lazarus_windows_cache"
          $Uri = 'http://consume.o2switch.net/lazarus/lazarus-4.0-fpc-3.2.2-win64.exe'
          $OutFile = "$Env:lazarus_windows_cache\lazarus-setup.exe"
          Invoke-WebRequest -Uri $Uri -OutFile $OutFile

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $Installer = "$Env:lazarus_windows_cache\lazarus-setup.exe"
          & $Installer /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART | Out-Null
          $Env:PATH += ';C:\Lazarus;C:\Lazarus\fpc\3.2.2\bin\x86_64-win64'
          instantfpc '-FuC:\Lazarus\components\lazutils' .github/workflows/make.pas
